-- The Regenerative Atlas library, as SQL.
--
-- Paste this into the Supabase project's SQL editor and run it, after
-- supabase/schema.sql has made the tables. Safe to run more than once:
-- sources are matched on their link, tags on their slug.
--
-- 28 sources, 52 tags. Written 2026-09-23.

-- The vocabulary first, so the ties below have something to point at.
insert into tags (slug, label, facet, note, core) values
  ('global', 'Global', 'location', 'Not bound to one place — planetary in scope, or read the same anywhere.', true),
  ('measurement', 'Measurement', 'method', 'Metrics, targets, benchmarks, verification.', true),
  ('building', 'Building', 'scale', 'The single building as the unit of work.', true),
  ('europe', 'Europe', 'location', 'Grounded in Europe.', true),
  ('ecology', 'Ecology', 'theme', 'Ecosystem function and succession as design grounding.', true),
  ('planetary', 'Planetary', 'scale', 'Global boundaries and budgets.', true),
  ('uk', 'UK', 'location', 'Grounded in the United Kingdom.', true),
  ('carbon', 'Carbon', 'theme', 'Embodied and operational carbon, drawdown, accounting.', true),
  ('framework', 'Framework', 'format', 'A structure for organising practice.', true),
  ('economics', 'Economics', 'theme', 'Value, cost, and the economic models underneath.', true),
  ('materials', 'Materials', 'material', 'Material culture, sourcing, specification.', true),
  ('circular-economy', 'Circular economy', 'theme', 'Keeping materials in use, designing out waste.', true),
  ('community', 'Community', 'theme', 'Who a project is for and who decides.', true),
  ('dataset', 'Dataset', 'format', 'Open data and databases.', true),
  ('energy', 'Energy', 'theme', 'Demand, supply, and the metabolism of buildings.', true),
  ('justice', 'Justice', 'theme', 'Who carries the cost and who receives the benefit.', true),
  ('regenerative-systems', 'Regenerative systems', 'theme', 'Whole-system thinking that leaves places healthier than it found them.', true),
  ('retrofit', 'Retrofit', 'method', 'Working with what already stands.', true),
  ('standard', 'Standard', 'format', 'Certification, protocol, formal requirement.', true),
  ('case-study', 'Case study', 'format', 'A built or attempted project, examined.', true),
  ('diagrams', 'Diagrams', 'format', 'Work whose value is in how it draws the idea.', true),
  ('governance', 'Governance', 'theme', 'Policy, procurement, ownership, regulation.', true),
  ('guidance', 'Guidance', 'format', 'Practical how-to for practitioners.', true),
  ('health', 'Health', 'theme', 'Human wellbeing, air, light, comfort, toxicity.', true),
  ('north-america', 'North America', 'location', 'Grounded in North America.', true),
  ('place', 'Place', 'theme', 'Working from the specific character of a site.', true),
  ('toolkit', 'Toolkit', 'format', 'Something you use, not only read.', true),
  ('biomimicry', 'Biomimicry', 'theme', 'Design that learns from how nature makes and adapts.', true),
  ('book', 'Book', 'format', 'Book-length work.', true),
  ('city', 'City', 'scale', 'Urban systems and municipal scale.', true),
  ('living-systems', 'Living systems', 'theme', 'Buildings and places understood as living, nested wholes.', true),
  ('pattern-language', 'Pattern language', 'method', 'Repeatable, named design moves.', true),
  ('product', 'Product', 'scale', 'Objects, components, assemblies.', true),
  ('report', 'Report', 'format', 'Institutional or industry publication.', true),
  ('storytelling', 'Storytelling', 'method', 'Narrative as a way of shifting practice.', true),
  ('usa', 'USA', 'location', 'Grounded in the United States.', true),
  ('bio-based', 'Bio-based', 'material', 'Materials grown rather than extracted.', true),
  ('biodiversity', 'Biodiversity', 'theme', 'Habitat, net gain, more-than-human inhabitants.', true),
  ('bioregion', 'Bioregion', 'scale', 'Watershed and landscape scale.', true),
  ('climate-adaptation', 'Climate adaptation', 'theme', 'Designing for the climate that is arriving.', true),
  ('definition', 'Definition', 'theme', 'Texts that argue what regenerative actually means.', true),
  ('degrowth', 'Degrowth', 'theme', 'Sufficiency, limits, building less.', true),
  ('essay', 'Essay', 'format', 'Shorter argued writing.', true),
  ('indigenous-knowledge', 'Indigenous knowledge', 'theme', 'Land relationships that long predate the field.', true),
  ('life-cycle-assessment', 'Life-cycle assessment', 'method', 'LCA, EPDs, whole-life measurement.', true),
  ('modelling', 'Modelling', 'method', 'Simulation, scenarios, digital tools.', true),
  ('neighbourhood', 'Neighbourhood', 'scale', 'Blocks, streets, shared ground.', true),
  ('paper', 'Paper', 'format', 'Peer-reviewed or academic writing.', true),
  ('reuse', 'Reuse', 'material', 'Salvage, second life, material passports.', true),
  ('soil', 'Soil', 'theme', 'Soil health, agriculture, ground as a living body.', true),
  ('straw', 'Straw', 'material', 'Straw bale and agricultural fibre construction.', true),
  ('systems-thinking', 'Systems thinking', 'method', 'Feedback, leverage, stocks and flows.', true)
on conflict (slug) do update set
  label = excluded.label, facet = excluded.facet, note = excluded.note, core = excluded.core;

-- The research.
insert into sources (url, url_key, title, authors, publisher, year, summary, note, contributor, status, origin, created_at) values
  ('https://www.architectscan.org/', 'architectscan.org/', 'Architects Climate Action Network', 'ACAN', 'ACAN', 2019, 'Organising within the profession — retrofit-first campaigning, embodied carbon regulation, and the argument for building less.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://rmi.org/', 'rmi.org/', 'RMI', 'Rocky Mountain Institute', 'RMI', 1982, 'Independent research on energy transition, from deep retrofit economics to embodied carbon in construction materials.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.passivhaustrust.org.uk/', 'passivhaustrust.org.uk/', 'Passivhaus Trust', 'Passivhaus Trust', 'Passivhaus Trust', 2010, 'The UK body for the Passivhaus standard — fabric-first energy performance verified by measurement rather than modelled intent.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://new-european-bauhaus.europa.eu/', 'new-european-bauhaus.europa.eu/', 'New European Bauhaus', 'European Commission', 'European Commission', 2020, 'The EU''s attempt to bind the Green Deal to beauty, sustainability and togetherness — and a live argument about whether aesthetics belong in climate policy.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.rewildingbritain.org.uk/', 'rewildingbritain.org.uk/', 'Rewilding Britain', 'Rewilding Britain', 'Rewilding Britain', 2015, 'Case studies and evidence for letting land recover its own processes, at the scale where ecological function actually returns.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://milkweed.org/book/braiding-sweetgrass', 'milkweed.org/book/braiding-sweetgrass', 'Braiding Sweetgrass', 'Robin Wall Kimmerer', 'Milkweed Editions', 2013, 'Indigenous knowledge and plant science held together, and the honourable harvest as a working ethic for taking anything from a living system.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.patternlanguage.com/', 'patternlanguage.com/', 'Pattern Language and The Nature of Order', 'Christopher Alexander', 'Center for Environmental Structure', 1977, 'Alexander''s argument that living structure emerges from repeated, named, locally-adapted moves — the ancestor of most attempts to write design knowledge down.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.bioregional.com/one-planet-living', 'bioregional.com/one-planet-living', 'One Planet Living', 'Bioregional', 'Bioregional', 2003, 'Ten principles for living within one planet''s resources, developed through BedZED and used since as a masterplanning framework.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.footprintnetwork.org/', 'footprintnetwork.org/', 'Global Footprint Network', 'Global Footprint Network', 'Global Footprint Network', 2003, 'Ecological footprint and biocapacity accounts by country — the source behind Earth Overshoot Day and most one-planet framings.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://drawdown.org/solutions', 'drawdown.org/solutions', 'Project Drawdown Solutions', 'Project Drawdown', 'Project Drawdown', 2017, 'Climate solutions ranked by modelled emissions impact, with the assumptions published — useful precisely because it lets you argue with the ranking.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://materialcultures.org/', 'materialcultures.org/', 'Material Cultures', 'Material Cultures', 'Material Cultures', 2019, 'Research and practice rebuilding a construction culture around bio-based materials grown in the landscapes that surround a site — straw, hemp, timber, earth.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.circularity-gap.world/', 'circularity-gap.world/', 'Circularity Gap Report', 'Circle Economy', 'Circle Economy', 2018, 'An annual measurement of what share of the global economy is actually circular. The number has been going the wrong way.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.bamb2020.eu/', 'bamb2020.eu/', 'Buildings As Material Banks', 'BAMB consortium', 'EU Horizon 2020', 2015, 'The project that developed material passports and reversible building design — treating a building as a temporary arrangement of materials that must be recoverable.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://ukgbc.org/', 'ukgbc.org/', 'UK Green Building Council', 'UKGBC', 'UKGBC', 2007, 'Home of the UK Net Zero Carbon Buildings Framework and the whole-life carbon roadmap for the sector.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.leti.uk/', 'leti.uk/', 'LETI', 'Low Energy Transformation Initiative', 'LETI', 2017, 'Volunteer-built guidance — the Climate Emergency Design Guide and the Embodied Carbon Primer — that turned UK net-zero targets into numbers a design team can work to.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.architecture.com/about/policy/climate-action/2030-climate-challenge', 'architecture.com/about/policy/climate-action/2030-climate-challenge', 'RIBA 2030 Climate Challenge', 'Royal Institute of British Architects', 'RIBA', 2019, 'Stepped targets to 2030 for operational energy, embodied carbon and potable water, given per square metre so projects can be held to them.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://carbonleadershipforum.org/', 'carbonleadershipforum.org/', 'Carbon Leadership Forum', 'Carbon Leadership Forum', 'University of Washington', 2010, 'Open research and open data on embodied carbon, including the EC3 tool and the material baselines most whole-life assessments are compared against.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.terrapinbrightgreen.com/reports/14-patterns/', 'terrapinbrightgreen.com/reports/14-patterns', '14 Patterns of Biophilic Design', 'William Browning, Catherine Ryan, Joseph Clancy', 'Terrapin Bright Green', 2014, 'Fourteen named, evidenced patterns for putting nature into buildings, each with the health outcome it is associated with.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://c2ccertified.org/', 'c2ccertified.org/', 'Cradle to Cradle Certified', 'Cradle to Cradle Products Innovation Institute', 'C2C PII', 2010, 'Product standard built on McDonough and Braungart''s argument that waste is a design error — material health, circularity, clean air, water, social fairness.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://living-future.org/lbc/', 'living-future.org/lbc', 'Living Building Challenge', 'International Living Future Institute', 'ILFI', 2006, 'A certification organised as seven petals and judged on measured performance over twelve months of occupation, not on prediction.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://biomimicry.net/', 'biomimicry.net/', 'Biomimicry 3.8', 'Janine Benyus and colleagues', 'Biomimicry 3.8', 1998, 'Consultancy behind Ecological Performance Standards, which set a project''s targets from what the intact local ecosystem would do on that same ground.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://asknature.org/', 'asknature.org/', 'AskNature', 'The Biomimicry Institute', 'Biomimicry Institute', 2008, 'A searchable library of biological strategies indexed by the design function they solve — how does nature manage water, resist fracture, cool itself.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.stockholmresilience.org/research/planetary-boundaries.html', 'stockholmresilience.org/research/planetary-boundaries.html', 'Planetary Boundaries', 'Johan Rockström, Will Steffen and colleagues', 'Stockholm Resilience Centre', 2009, 'The nine processes that regulate the stability of the Earth system, and how far past several of them we already are. The ceiling that regenerative targets are measured against.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://doughnuteconomics.org/', 'doughnuteconomics.org/', 'Doughnut Economics Action Lab', 'Kate Raworth and DEAL', 'DEAL', 2019, 'Tools for working between the social foundation and the ecological ceiling, including the city portrait method used to downscale planetary boundaries to a place.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://www.ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview', 'ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview', 'Circular Economy Introduction', 'Ellen MacArthur Foundation', 'Ellen MacArthur Foundation', 2013, 'The butterfly diagram and the three principles — eliminate waste, circulate materials, regenerate nature. The most-borrowed diagram in the field.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://regenesisgroup.com/', 'regenesisgroup.com/', 'Regenesis Group', 'Pamela Mang, Bill Reed, Ben Haggard', 'Regenesis', 1995, 'The practice that developed story-of-place as a working method: read the living system of a site before proposing anything, and design so the place can keep evolving.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://doi.org/10.1080/09613210701475753', 'doi.org/10.1080/09613210701475753', 'Shifting from ''sustainability'' to regeneration', 'Bill Reed', 'Building Research & Information', 2007, 'The paper that drew the trajectory from degenerative through neutral to regenerative practice, and argued that doing less harm is not a destination.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz),
  ('https://donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system/', 'donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system', 'Leverage Points: Places to Intervene in a System', 'Donella Meadows', 'The Donella Meadows Project', 1999, 'Twelve places to intervene in a system, ordered from the shallow (adjusting numbers) to the deep (changing the paradigm the system arises from). The foundational text for why regenerative work is rarely a technical problem.', null, null, 'published', 'seed', '2026-09-15 07:45:54'::timestamptz)
on conflict (url_key) do nothing;

-- What is filed where. Matched on the link and the slug, so no ids are
-- written down anywhere and the file stays true whatever order things
-- were inserted in.
insert into source_tags (source_id, tag_id)
select s.id, t.id from sources s, tags t where (s.url_key, t.slug) in (
  ('architectscan.org/', 'europe'),
  ('architectscan.org/', 'uk'),
  ('architectscan.org/', 'retrofit'),
  ('architectscan.org/', 'community'),
  ('architectscan.org/', 'degrowth'),
  ('architectscan.org/', 'governance'),
  ('architectscan.org/', 'justice'),
  ('rmi.org/', 'report'),
  ('rmi.org/', 'north-america'),
  ('rmi.org/', 'usa'),
  ('rmi.org/', 'retrofit'),
  ('rmi.org/', 'carbon'),
  ('rmi.org/', 'economics'),
  ('rmi.org/', 'energy'),
  ('passivhaustrust.org.uk/', 'standard'),
  ('passivhaustrust.org.uk/', 'europe'),
  ('passivhaustrust.org.uk/', 'uk'),
  ('passivhaustrust.org.uk/', 'measurement'),
  ('passivhaustrust.org.uk/', 'retrofit'),
  ('passivhaustrust.org.uk/', 'building'),
  ('passivhaustrust.org.uk/', 'energy'),
  ('new-european-bauhaus.europa.eu/', 'framework'),
  ('new-european-bauhaus.europa.eu/', 'europe'),
  ('new-european-bauhaus.europa.eu/', 'city'),
  ('new-european-bauhaus.europa.eu/', 'community'),
  ('new-european-bauhaus.europa.eu/', 'governance'),
  ('new-european-bauhaus.europa.eu/', 'justice'),
  ('rewildingbritain.org.uk/', 'case-study'),
  ('rewildingbritain.org.uk/', 'europe'),
  ('rewildingbritain.org.uk/', 'uk'),
  ('rewildingbritain.org.uk/', 'bioregion'),
  ('rewildingbritain.org.uk/', 'biodiversity'),
  ('rewildingbritain.org.uk/', 'ecology'),
  ('rewildingbritain.org.uk/', 'soil'),
  ('milkweed.org/book/braiding-sweetgrass', 'book'),
  ('milkweed.org/book/braiding-sweetgrass', 'north-america'),
  ('milkweed.org/book/braiding-sweetgrass', 'storytelling'),
  ('milkweed.org/book/braiding-sweetgrass', 'ecology'),
  ('milkweed.org/book/braiding-sweetgrass', 'indigenous-knowledge'),
  ('milkweed.org/book/braiding-sweetgrass', 'justice'),
  ('patternlanguage.com/', 'book'),
  ('patternlanguage.com/', 'global'),
  ('patternlanguage.com/', 'pattern-language'),
  ('patternlanguage.com/', 'building'),
  ('patternlanguage.com/', 'community'),
  ('patternlanguage.com/', 'living-systems'),
  ('bioregional.com/one-planet-living', 'case-study'),
  ('bioregional.com/one-planet-living', 'framework'),
  ('bioregional.com/one-planet-living', 'global'),
  ('bioregional.com/one-planet-living', 'neighbourhood'),
  ('bioregional.com/one-planet-living', 'planetary'),
  ('bioregional.com/one-planet-living', 'community'),
  ('footprintnetwork.org/', 'dataset'),
  ('footprintnetwork.org/', 'global'),
  ('footprintnetwork.org/', 'measurement'),
  ('footprintnetwork.org/', 'planetary'),
  ('footprintnetwork.org/', 'ecology'),
  ('footprintnetwork.org/', 'economics'),
  ('drawdown.org/solutions', 'dataset'),
  ('drawdown.org/solutions', 'global'),
  ('drawdown.org/solutions', 'measurement'),
  ('drawdown.org/solutions', 'modelling'),
  ('drawdown.org/solutions', 'planetary'),
  ('drawdown.org/solutions', 'carbon'),
  ('materialcultures.org/', 'case-study'),
  ('materialcultures.org/', 'europe'),
  ('materialcultures.org/', 'uk'),
  ('materialcultures.org/', 'bio-based'),
  ('materialcultures.org/', 'materials'),
  ('materialcultures.org/', 'straw'),
  ('materialcultures.org/', 'place'),
  ('circularity-gap.world/', 'report'),
  ('circularity-gap.world/', 'global'),
  ('circularity-gap.world/', 'measurement'),
  ('circularity-gap.world/', 'planetary'),
  ('circularity-gap.world/', 'circular-economy'),
  ('circularity-gap.world/', 'economics'),
  ('bamb2020.eu/', 'toolkit'),
  ('bamb2020.eu/', 'europe'),
  ('bamb2020.eu/', 'materials'),
  ('bamb2020.eu/', 'reuse'),
  ('bamb2020.eu/', 'building'),
  ('bamb2020.eu/', 'circular-economy'),
  ('ukgbc.org/', 'framework'),
  ('ukgbc.org/', 'europe'),
  ('ukgbc.org/', 'uk'),
  ('ukgbc.org/', 'measurement'),
  ('ukgbc.org/', 'building'),
  ('ukgbc.org/', 'carbon'),
  ('ukgbc.org/', 'governance'),
  ('leti.uk/', 'guidance'),
  ('leti.uk/', 'europe'),
  ('leti.uk/', 'uk'),
  ('leti.uk/', 'retrofit'),
  ('leti.uk/', 'building'),
  ('leti.uk/', 'carbon'),
  ('leti.uk/', 'energy'),
  ('architecture.com/about/policy/climate-action/2030-climate-challenge', 'guidance'),
  ('architecture.com/about/policy/climate-action/2030-climate-challenge', 'europe'),
  ('architecture.com/about/policy/climate-action/2030-climate-challenge', 'uk'),
  ('architecture.com/about/policy/climate-action/2030-climate-challenge', 'measurement'),
  ('architecture.com/about/policy/climate-action/2030-climate-challenge', 'building'),
  ('architecture.com/about/policy/climate-action/2030-climate-challenge', 'carbon'),
  ('architecture.com/about/policy/climate-action/2030-climate-challenge', 'energy'),
  ('carbonleadershipforum.org/', 'dataset'),
  ('carbonleadershipforum.org/', 'north-america'),
  ('carbonleadershipforum.org/', 'usa'),
  ('carbonleadershipforum.org/', 'materials'),
  ('carbonleadershipforum.org/', 'life-cycle-assessment'),
  ('carbonleadershipforum.org/', 'measurement'),
  ('carbonleadershipforum.org/', 'carbon'),
  ('terrapinbrightgreen.com/reports/14-patterns', 'guidance'),
  ('terrapinbrightgreen.com/reports/14-patterns', 'global'),
  ('terrapinbrightgreen.com/reports/14-patterns', 'pattern-language'),
  ('terrapinbrightgreen.com/reports/14-patterns', 'building'),
  ('terrapinbrightgreen.com/reports/14-patterns', 'ecology'),
  ('terrapinbrightgreen.com/reports/14-patterns', 'health'),
  ('c2ccertified.org/', 'standard'),
  ('c2ccertified.org/', 'global'),
  ('c2ccertified.org/', 'materials'),
  ('c2ccertified.org/', 'product'),
  ('c2ccertified.org/', 'circular-economy'),
  ('c2ccertified.org/', 'health'),
  ('living-future.org/lbc', 'standard'),
  ('living-future.org/lbc', 'global'),
  ('living-future.org/lbc', 'measurement'),
  ('living-future.org/lbc', 'building'),
  ('living-future.org/lbc', 'health'),
  ('living-future.org/lbc', 'regenerative-systems'),
  ('biomimicry.net/', 'standard'),
  ('biomimicry.net/', 'global'),
  ('biomimicry.net/', 'measurement'),
  ('biomimicry.net/', 'biomimicry'),
  ('biomimicry.net/', 'ecology'),
  ('biomimicry.net/', 'place'),
  ('asknature.org/', 'dataset'),
  ('asknature.org/', 'toolkit'),
  ('asknature.org/', 'global'),
  ('asknature.org/', 'product'),
  ('asknature.org/', 'biomimicry'),
  ('asknature.org/', 'ecology'),
  ('stockholmresilience.org/research/planetary-boundaries.html', 'diagrams'),
  ('stockholmresilience.org/research/planetary-boundaries.html', 'global'),
  ('stockholmresilience.org/research/planetary-boundaries.html', 'measurement'),
  ('stockholmresilience.org/research/planetary-boundaries.html', 'planetary'),
  ('stockholmresilience.org/research/planetary-boundaries.html', 'climate-adaptation'),
  ('stockholmresilience.org/research/planetary-boundaries.html', 'ecology'),
  ('doughnuteconomics.org/', 'toolkit'),
  ('doughnuteconomics.org/', 'global'),
  ('doughnuteconomics.org/', 'city'),
  ('doughnuteconomics.org/', 'planetary'),
  ('doughnuteconomics.org/', 'economics'),
  ('doughnuteconomics.org/', 'justice'),
  ('ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview', 'diagrams'),
  ('ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview', 'framework'),
  ('ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview', 'global'),
  ('ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview', 'materials'),
  ('ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview', 'circular-economy'),
  ('ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview', 'economics'),
  ('regenesisgroup.com/', 'framework'),
  ('regenesisgroup.com/', 'global'),
  ('regenesisgroup.com/', 'storytelling'),
  ('regenesisgroup.com/', 'living-systems'),
  ('regenesisgroup.com/', 'place'),
  ('regenesisgroup.com/', 'regenerative-systems'),
  ('doi.org/10.1080/09613210701475753', 'diagrams'),
  ('doi.org/10.1080/09613210701475753', 'paper'),
  ('doi.org/10.1080/09613210701475753', 'global'),
  ('doi.org/10.1080/09613210701475753', 'building'),
  ('doi.org/10.1080/09613210701475753', 'definition'),
  ('doi.org/10.1080/09613210701475753', 'regenerative-systems'),
  ('donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system', 'essay'),
  ('donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system', 'framework'),
  ('donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system', 'global'),
  ('donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system', 'systems-thinking'),
  ('donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system', 'planetary'),
  ('donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system', 'regenerative-systems')
) on conflict do nothing;
